### ISSUE TITLE
Proxy server receives invalid response

### ISSUE THREAD

**Issue by spadavec** [chembl/chembl_webresource_client#29]
When I run the following code to get the smiles/ids/ic50s for a particular CHEMBL target: 

```
for x in chembl_ids:
    if x not in existing_files:
        print "Checking kinase id {}".format(x)
        res = activity.filter(target_chembl_id='{}'.format(x), relation='=', assay_type='B', standard_type="IC50")

        for sub in res:
            if sub['parent_molecule_chembl_id'] and sub['canonical_smiles'] and sub['standard_value'] is not None:
                ids.append(str(sub['parent_molecule_chembl_id']))
                smiles.append(str(sub['canonical_smiles']))
                ic50.append(float(sub['standard_value']))
        temp = map(lambda x, y, z: [x,y,z], ids, smiles, ic50)
        clean = []
        for z in temp:
            if z[0] not in [m[0] for m in clean]:
                clean.append(z)
```

I get the following error: 

```
Traceback (most recent call last):
  File "fetch-data.py", line 48, in <module>
    for sub in res:
  File "/home/spadavec/miniconda2/envs/rdkit/lib/python2.7/site-packages/chembl_webresource_client/query_set.py", line 116, in next
    self.chunk = self.query.next_page()
  File "/home/spadavec/miniconda2/envs/rdkit/lib/python2.7/site-packages/chembl_webresource_client/url_query.py", line 445, in next_page
    return self.get_page()
  File "/home/spadavec/miniconda2/envs/rdkit/lib/python2.7/site-packages/chembl_webresource_client/url_query.py", line 406, in get_page
    handle_http_error(res)
  File "/home/spadavec/miniconda2/envs/rdkit/lib/python2.7/site-packages/chembl_webresource_client/http_errors.py", line 113, in handle_http_error
    raise exception_class(request.url, request.text)
chembl_webresource_client.http_errors.HttpBadGateway: Error for url https://www.ebi.ac.uk/chembl/api/data/activity.json, server response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/chembl/api/data/activity.json">POST&nbsp;/chembl/api/data/activity.json</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at www.ebi.ac.uk Port 80</address>
</body></html>
```
Am I doing something wrong, or is this an error with too many requests being made (I want to make ~500 sequential requests)

**Comment by mnowotka** [comment]
You are doing everything fine. If the request takes too much time to process (due to compelex SQL) you get 502. This is related to #28 and I need to increase a timout so this error will dissapear. This should be done tomorrow. In the meantime all I can suggest is keep making requests until they succeed.

**Comment by spadavec** [comment]
Ah! My apologies for not seeing that issue. Thanks for pointing me in the right direction--I'll just ask it to sleep a little between requests.
