### ISSUE TITLE
pip install fails (python 2.7.12)

### ISSUE THREAD

**Issue by flc** [chembl/chembl_webresource_client#56]
```
Collecting unittest2py3k (from unittest2six->chembl_webresource_client)
  Using cached https://files.pythonhosted.org/packages/4e/3d/d44421e8d828af1399c1509c196db92e2a58f3764b01a0ee928d7025d1ca/unittest2py3k-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-NSvIsU/unittest2py3k/setup.py", line 12, in <module>
        from unittest2 import __version__ as VERSION
      File "unittest2/__init__.py", line 61, in <module>
        from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
      File "unittest2/case.py", line 539
        def assertAlmostEqual(self, first, second, *, places=None, msg=None,
                                                    ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-NSvIsU/unittest2py3k/
```

**Comment by eloyfelix** [comment]
We dropped Py2 compatibility as it will be deprecated in 3 months: https://pythonclock.org/

Please install the new version in Python3 using pip. 
```
pip install chembl-webresource-client
```
