### ISSUE TITLE
import and Conda install error 

### ISSUE THREAD

**Issue by zeromtmu** [chembl/chembl_webresource_client#62]
I used 
`from chembl_webresource_client.new_client import new_client`
and get this error 

```
Traceback (most recent call last):

  File "/anaconda3/envs/QSAR/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-54c833032a72>", line 1, in <module>
    from chembl_webresource_client.new_client import new_client

  File "/anaconda3/envs/QSAR/lib/python3.7/site-packages/chembl_webresource_client/__init__.py", line 24, in <module>
    from chembl_webresource_client.assay_resource import AssayResource

  File "/anaconda3/envs/QSAR/lib/python3.7/site-packages/chembl_webresource_client/assay_resource.py", line 3, in <module>
    from chembl_webresource_client.web_resource import WebResource

  File "/anaconda3/envs/QSAR/lib/python3.7/site-packages/chembl_webresource_client/web_resource.py", line 184
    def _get_one(self, url, async, frmt, method='get', data=None):
                                ^
SyntaxError: invalid syntax
```

and I try to reinstall but get some error

```
Package wheel conflicts for:
chembl_webresource_client -> python[version='>=3.5,<3.6.0a0'] -> pip -> wheel
python=3.7 -> pip -> wheel
Package pip conflicts for:
chembl_webresource_client -> python[version='>=3.5,<3.6.0a0'] -> pip
python=3.7 -> pip
Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09']
chembl_webresource_client -> python[version='>=3.5,<3.6.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09']
Package six conflicts for:
chembl_webresource_client -> six
chembl_webresource_client -> unittest2six -> unittest2 -> six[version='>=1.4|>=1.4.1|>=1.5.2']
Package ca-certificates conflicts for:
python=3.7 -> openssl[version='>=1.1.1c,<1.1.2a'] -> ca-certificates
chembl_webresource_client -> python[version='>=3.5,<3.6.0a0'] -> ca-certificates
Package setuptools conflicts for:
python=3.7 -> pip -> setuptools
chembl_webresource_client -> python[version='>=3.5,<3.6.0a0'] -> pip -> setuptools
```

what can i do?

**Comment by eloyfelix** [comment]
We are currently updating the library but there are no installable packages yet. If you want to try it before we build the packages you can install it from our master branch using pip:

```
pip install https://github.com/chembl/chembl_webresource_client/archive/master.zip
```

**Comment by eloyfelix** [comment]
you can now install it via pypi respository:

```
pip install chembl_webresource_client
```
